server {
    listen 80;
    include /etc/nginx/mime.types;
    root /usr/share/nginx/html;
    index index.html;

    # 1. Основной блок для SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Блок для статики (ассеты Vite)
    location /assets/ {
        # Важно: здесь мы НЕ используем try_files до index.html, 
        # чтобы не получать HTML вместо JS при ошибках.
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public";
        access_log off;
    }

    # 3. Общий блок для картинок и прочего
    location ~* \.(?:jpg|jpeg|gif|png|ico|svg|webp)$ {
        expires 1y;
        add_header Cache-Control "public";
        access_log off;
    }

    # Сжатие
    gzip on;
    gzip_proxied any;
    gzip_types text/plain text/css application/javascript application/json;
    gzip_min_length 1000;
}